### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
Your starter package, as requested in #1 :smiley: And as said, be welcome to my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to build on it. Should you have any questions, just ask.

### CODE REVIEW

**Comment by Smooth-E** [comment]
Thanks! I updated the metadata with new graphics and better wording (well, this is what the commit message says 😅). Merging it now.

**Comment by Smooth-E** [comment]
Okay, no. I forgot about changelogs. 

Actually, If I modify the APK asset for the 1.1 release to have a different version and number, will you add it to the store too? Don't think that it is necessary tho.

**Comment by Smooth-E** [comment]
I have modified the `1.1` release to include another APK file with fixed versioning. You are now free to include all of the three versions available into your repository. I have also added changelogs for all of these three versions and have updated metadata a bit as a whole.

**Comment by IzzySoft** [comment]
> Actually, If I modify the APK asset for the 1.1 release

Nope. Why adding older releases? 1.2 is already there. Newer release will however be picked up when they become available. I however have now manually triggered my updater to fetch the current Fastlane, so it will be updated on the server with the next sync (around 6 pm UTC).

And before you ask: My repo keeps the latest 3 versions or max 30 MB per app (whichever limit is reached first). So when the next release is fetched, v1.2 will stay available. I just don't add historical versions without a good reason :wink:

So thanks for merging! :smiley:

**Pull request merged**
